package com.example;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import io.github.bonigarcia.wdm.WebDriverManager;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.testng.annotations.Test;

import java.io.*;
import java.nio.file.Files;
import java.nio.file.Path;

public class SalesforceUsernameTest {

    @Test
    public void runLoginFlowAndGenerateReport() throws Exception {
        // 1) read username from username.json (repo root)
        Path projectRoot = Path.of(System.getProperty("user.dir"));
        Path jsonPath = projectRoot.resolve("username.json");
        if (!Files.exists(jsonPath)) {
            throw new RuntimeException("username.json not found at: " + jsonPath);
        }
        String jsonText = Files.readString(jsonPath);
        JsonObject obj = JsonParser.parseString(jsonText).getAsJsonObject();
        String username = obj.has("username") ? obj.get("username").getAsString() : "";

        // 2) prepare output folder
        Path reportDir = projectRoot.resolve("docs");
        Files.createDirectories(reportDir);

        // 3) start headless Chrome
        WebDriverManager.chromedriver().setup();
        ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless=new"); // new headless mode
        options.addArguments("--no-sandbox");
        options.addArguments("--disable-dev-shm-usage");
        options.addArguments("--window-size=1280,1024");
        WebDriver driver = new ChromeDriver(options);

        try {
            // go to Salesforce login
            driver.get("https://login.salesforce.com/");

            // wait briefly for the username field (simple approach)
            Thread.sleep(1500);

            // find username field (Salesforce username field id is "username")
            WebElement usernameField = driver.findElement(By.id("username"));

            // Step 1: fill value and take screenshot
            usernameField.sendKeys(username);
            takeScreenshot(driver, reportDir.resolve("step1.png"));

            // Step 2: empty value and take screenshot
            usernameField.clear();
            takeScreenshot(driver, reportDir.resolve("step2.png"));

            // create HTML report
            Path html = reportDir.resolve("report.html");
            String htmlContent = buildHtmlReport();
            Files.writeString(html, htmlContent);

        } finally {
            // close browser
            driver.quit();
        }
    }

    private void takeScreenshot(WebDriver driver, Path outPath) throws IOException {
        if (driver instanceof TakesScreenshot ts) {
            File src = ts.getScreenshotAs(OutputType.FILE);
            Files.copy(src.toPath(), outPath);
        } else {
            throw new IOException("Driver does not support screenshots");
        }
    }

    private String buildHtmlReport() {
        // Simple 3x3 table as requested (No., Steps, Screenshot)
        return """
                <!doctype html>
                <html>
                <head>
                  <meta charset="utf-8"/>
                  <title>Test Report</title>
                  <style>
                    body { font-family: Arial, Helvetica, sans-serif; padding: 20px; }
                    table { border-collapse: collapse; width: 100%; }
                    th, td { border: 1px solid #ddd; padding: 8px; text-align: left; vertical-align: top; }
                    th { background: #f4f4f4; }
                    img { max-width: 400px; height: auto; border: 1px solid #ccc; }
                  </style>
                </head>
                <body>
                  <h2>Test Report</h2>
                  <table>
                    <tr><th>No.</th><th>Steps</th><th>Screenshot</th></tr>
                    <tr>
                      <td>1.</td>
                      <td>Fill value in username field.</td>
                      <td><a href="step1.png" target="_blank"><img src="step1.png" alt="step1"></a></td>
                    </tr>
                    <tr>
                      <td>2.</td>
                      <td>Empty value in username field.</td>
                      <td><a href="step2.png" target="_blank"><img src="step2.png" alt="step2"></a></td>
                    </tr>
                    <tr>
                      <td>3.</td>
                      <td>Summary</td>
                      <td>Generated by Selenium test</td>
                    </tr>
                  </table>
                </body>
                </html>
                """;
    }
}
